using System;

namespace NeeView.Interop
{
    [Flags]
    public enum FileAttributes
    {
        FILE_ATTRIBUTE_READONLY = 0x0001,
        FILE_ATTRIBUTE_HIDDEN = 0x0002,
        FILE_ATTRIBUTE_SYSTEM = 0x0004,
        FILE_ATTRIBUTE_DIRECTORY = 0x0010,
        FILE_ATTRIBUTE_ARCHIVE = 0x0020,
        FILE_ATTRIBUTE_ENCRYPTED = 0x0040,
        FILE_ATTRIBUTE_NORMAL = 0x0080,
        FILE_ATTRIBUTE_TEMPORARY = 0x0100,
        FILE_ATTRIBUTE_SPARSE_FILE = 0x0200,
        FILE_ATTRIBUTE_REPARSE_POINT = 0x0400,
        FILE_ATTRIBUTE_COMPRESSED = 0x0800,
        FILE_ATTRIBUTE_OFFLINE = 0x1000,
    }
}
